version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: development
      MYSQL_DATABASE: expenses
      MYSQL_USER: user
      MYSQL_PASSWORD: development
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3307:3306"
