version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: development
      MYSQL_DATABASE: expenses
      MYSQL_USER: user
      MYSQL_PASSWORD: development
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - expense-network
  expense:
    container_name: expenses-api
    restart: on-failure
    build:
      dockerfile: Dockerfile
    image: expenses-api
    environment:
      SPRING.DATASOURCE.URL: jdbc:mariadb://db:3306/expenses?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: user
      SPRING.DATASOURCE.PASSWORD: development
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - expense-network

networks:
  expense-network:
    driver: bridge

